* `ux-autocomplete`_: Transform ``EntityType``, ``ChoiceType`` or *any* ``<select>`` element into an Ajax-powered autocomplete field
* `ux-chartjs`_: Easy charts with `Chart.js`_
* `ux-cropperjs`_: Form Type and tools for cropping images
* `ux-dropzone`_: Form Type for stylized "drop zone" for file uploads
* `ux-lazy-image`_: Optimize Image Loading with BlurHash
* `ux-live-component`_: Build Dynamic Interfaces with Zero JavaScript
* `ux-notify`_: Send server-sent native notification with Mercure
* `ux-react`_: Render `React`_ component from Twig
* `ux-swup`_: Integration with `Swup`_
* `ux-turbo`_: Integration with `Turbo Drive`_ for a single-page-app experience
* `ux-twig-component`_: Build Twig Components Backed by a PHP Class
* `ux-typed`_: Integration with `Typed`_

.. _`ux-autocomplete`: https://symfony.com/bundles/ux-autocomplete/current/index.html
.. _`ux-chartjs`: https://symfony.com/bundles/ux-chartjs/current/index.html
.. _`ux-cropperjs`: https://symfony.com/bundles/ux-cropperjs/current/index.html
.. _`ux-dropzone`: https://symfony.com/bundles/ux-dropzone/current/index.html
.. _`ux-lazy-image`: https://symfony.com/bundles/ux-lazy-image/current/index.html
.. _`ux-live-component`: https://symfony.com/bundles/ux-live-component/current/index.html
.. _`ux-notify`: https://symfony.com/bundles/ux-notify/current/index.html
.. _`ux-react`: https://symfony.com/bundles/ux-react/current/index.html
.. _`ux-swup`: https://symfony.com/bundles/ux-swup/current/index.html
.. _`ux-turbo`: https://symfony.com/bundles/ux-turbo/current/index.html
.. _`ux-twig-component`: https://symfony.com/bundles/ux-twig-component/current/index.html
.. _`ux-typed`: https://symfony.com/bundles/ux-typed/current/index.html
.. _`Chart.js`: https://www.chartjs.org/
.. _`Swup`: https://swup.js.org/
.. _`React`: https://reactjs.org/
.. _`Turbo Drive`: https://turbo.hotwired.dev/
.. _`Typed`: https://github.com/mattboldt/typed.js/
