* `ux-turbo`_: Integration with `Turbo Drive`_ for a single-page-app experience
* `ux-live-component`_: Build Dynamic Interfaces with Zero JavaScript
* `ux-twig-component`_: Build Twig Components Backed by a PHP Class
* `ux-chartjs`_: Easy charts with Chart.js
* `ux-lazy-image`_: Optimize Image Loading with BlurHash
* `ux-cropperjs`_: Form Type and tools for cropping images
* `ux-dropzone`_: Form type for stylized "drop zone" for file uploads
* `ux-swup`_: Integration with Swup

.. _`ux-turbo`: https://symfony.com/bundles/ux-turbo/current/index.html
.. _`ux-live-component`: https://symfony.com/bundles/ux-live-component/current/index.html
.. _`ux-twig-component`: https://symfony.com/bundles/ux-twig-component/current/index.html
.. _`ux-chartjs`: https://symfony.com/bundles/ux-chartjs/current/index.html
.. _`ux-lazy-image`: https://symfony.com/bundles/ux-lazy-image/current/index.html
.. _`ux-cropperjs`: https://symfony.com/bundles/ux-cropperjs/current/index.html
.. _`ux-dropzone`: https://symfony.com/bundles/ux-dropzone/current/index.html
.. _`ux-swup`: https://symfony.com/bundles/ux-swup/current/index.html
.. _`Turbo Drive`: https://turbo.hotwired.dev/
