imports:
    - { resource: config_dev.yml }

web.config:
    error_handler: false

webprofiler.config:
    toolbar: false
    intercept_redirects: false

zend.logger:
    priority: debug

web.test: ~
