imports:
    - { resource: config.yml }

web.config:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

webprofiler.config:
    toolbar: true
    intercept_redirects: true

zend.logger:
    priority: debug
    path:     %kernel.root_dir%/logs/%kernel.environment%.log
