imports:
    - { resource: config_dev.yml }

kernel.config:
    error_handler: false

webprofiler.config:
    toolbar: false
    intercept_redirects: false

zend.logger:
    priority: debug

kernel.test: ~
