#!/usr/bin/env php
<?php

require_once __DIR__.'/HelloKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new HelloKernel('dev', true);

$application = new Application($kernel);
$application->run();
