alpha3
~~~~~~

**type**: ``boolean`` **default**: ``false``

If this option is ``true``, the choice values use the `ISO 3166-1 alpha-3`_
three-letter codes (e.g. New Zealand = ``NZL``) instead of the default
`ISO 3166-1 alpha-2`_ two-letter codes (e.g. New Zealand = ``NZ``).

.. _`ISO 3166-1 alpha-2`: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
.. _`ISO 3166-1 alpha-3`: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
