``constraints``
~~~~~~~~~~~~~~~

**type**: ``array`` or :class:`Symfony\\Component\\Validator\\Constraint` **default**: ``[]``

Allows you to attach one or more validation constraints to a specific field.
For more information, see :ref:`Adding Validation <form-option-constraints>`.
This option is added in the :class:`Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension`
form extension.
