inherit_data
~~~~~~~~~~~~

.. versionadded:: 2.3
    The ``inherit_data`` option was introduced in Symfony 2.3. Before, it
    was known as ``virtual``.

**type**: ``boolean`` **default**: ``false``

This option determines if the form will inherit data from its parent form.
This can be useful is you have a set of fields that are duplicated across
multiple forms. See :doc:`/cookbook/form/inherit_data_option`.
