priority
~~~~~~~~

**type**: ``integer`` **default**: ``0``

    Allows you to set the field rendering priority. This option will affect
    the view order only, sorting all fields in order of importance instead of
    simply numerical order, i.e. fields with higher priority will be rendered
    first, fields with lower priority will be rendered last and fields with
    equal priority will keep the original order.
