Select Tag, Checkboxes or Radio Buttons
---------------------------------------

This field may be rendered as one of several different HTML fields, depending
on the ``expanded`` and ``multiple`` options:

========================================  =========  =========
Element Type                              Expanded   Multiple
========================================  =========  =========
select tag                                ``false``  ``false``
select tag (with ``multiple`` attribute)  ``false``  ``true``
radio buttons                             ``true``   ``false``
checkboxes                                ``true``   ``true``
========================================  =========  =========
