* **The Class Loader Component**

  * :doc:`/components/class_loader`

* **The Console Component**

  * :doc:`/components/console`

* **The CSS Selector Component**

  * :doc:`/components/css_selector`

* :doc:`/components/dependency_injection/index`

  * :doc:`/components/dependency_injection/introduction`

* :doc:`/components/event_dispatcher/index`

  * :doc:`/components/event_dispatcher/introduction`

* **The DOM Crawler Component**

  * :doc:`/components/dom_crawler`

* **The Finder Component**

  * :doc:`/components/finder`

* :doc:`/components/http_foundation/index`

  * :doc:`/components/http_foundation/introduction`

* **The Locale Component**

  * :doc:`/components/locale`

* **The Process Component**

  * :doc:`/components/process`

* **The Routing Component**

  * :doc:`/components/routing`

* **The Templating Component**

  * :doc:`/components/templating`

* **The YAML Component**

  * :doc:`/components/yaml`
