* **Bundle Configuration**:

  * :doc:`FrameworkBundle (framework) </reference/configuration/framework>`
  * :doc:`AsseticBundle (assetic) </reference/configuration/assetic>`
  * :doc:`DoctrineBundle (doctrine) </reference/configuration/doctrine>`
  * :doc:`SecurityBundle (security) </reference/configuration/security>`
  * :doc:`SwiftMailerBundle (swiftmailer) </reference/configuration/swiftmailer>`
  * :doc:`TwigBundle (twig) </reference/configuration/twig>`
  * :doc:`MonologBundle (monolog) </reference/configuration/monolog>`
  * :doc:`WebProfilerBundle (web_profiler) </reference/configuration/web_profiler>`
  * :doc:`DoctrineMongoDBBundle (doctrine_mongodb) </reference/configuration/mongodb>`

* **Forms**

  * :doc:`Form Field Type Reference</reference/forms/types>`
  * :doc:`Twig Template Function Reference</reference/forms/twig_reference>`

* **Other Areas**

  * :doc:`/reference/constraints`
  * :doc:`/reference/dic_tags`
  * :doc:`/reference/YAML`
  * :doc:`/reference/requirements`
  * :doc:`/reference/model`
