Text Fields
~~~~~~~~~~~

* :doc:`TextType </forms/types/text>`
* :doc:`TextareaType </forms/types/textarea>`
* :doc:`EmailType </forms/types/email>`
* :doc:`IntegerType </forms/types/integer>`
* :doc:`MoneyType </forms/types/money>`
* :doc:`NumberType </forms/types/number>`
* :doc:`PasswordType </forms/types/password>`
* :doc:`PercentType </forms/types/percent>`
* :doc:`SearchType </forms/types/search>`
* :doc:`UrlType </forms/types/url>`
* :doc:`RangeType </forms/types/range>`
* :doc:`TelType </forms/types/tel>`
* :doc:`ColorType </forms/types/color>`

Choice Fields
~~~~~~~~~~~~~

* :doc:`ChoiceType </forms/types/choice>`
* :doc:`EnumType </forms/types/enum>`
* :doc:`EntityType </forms/types/entity>`
* :doc:`CountryType </forms/types/country>`
* :doc:`LanguageType </forms/types/language>`
* :doc:`LocaleType </forms/types/locale>`
* :doc:`TimezoneType </forms/types/timezone>`
* :doc:`CurrencyType </forms/types/currency>`

Date and Time Fields
~~~~~~~~~~~~~~~~~~~~

* :doc:`DateType </forms/types/date>`
* :doc:`DateIntervalType </forms/types/dateinterval>`
* :doc:`DateTimeType </forms/types/datetime>`
* :doc:`TimeType </forms/types/time>`
* :doc:`BirthdayType </forms/types/birthday>`
* :doc:`WeekType </forms/types/week>`

Other Fields
~~~~~~~~~~~~

* :doc:`CheckboxType </forms/types/checkbox>`
* :doc:`FileType </forms/types/file>`
* :doc:`RadioType </forms/types/radio>`

Symfony UX Fields
~~~~~~~~~~~~~~~~~

These types are part of the :doc:`Symfony UX initiative </frontend/ux>`:

* `CropperType`_ (using Cropper.js)
* `DropzoneType`_

UID Fields
~~~~~~~~~~

* :doc:`UuidType </forms/types/uuid>`
* :doc:`UlidType </forms/types/ulid>`

Field Groups
~~~~~~~~~~~~

* :doc:`CollectionType </forms/types/collection>`
* :doc:`RepeatedType </forms/types/repeated>`

Hidden Fields
~~~~~~~~~~~~~

* :doc:`HiddenType </forms/types/hidden>`

Buttons
~~~~~~~

* :doc:`ButtonType </forms/types/button>`
* :doc:`ResetType </forms/types/reset>`
* :doc:`SubmitType </forms/types/submit>`

Base Fields
~~~~~~~~~~~

* :doc:`FormType </forms/types/form>`

.. _`CropperType`: https://github.com/symfony/ux/tree/2.x/src/Cropperjs#readme
.. _`DropzoneType`: https://github.com/symfony/ux/tree/2.x/src/Dropzone#readme
