Text Fields
~~~~~~~~~~~

* :doc:`TextType </reference/forms/types/text>`
* :doc:`TextareaType </reference/forms/types/textarea>`
* :doc:`EmailType </reference/forms/types/email>`
* :doc:`IntegerType </reference/forms/types/integer>`
* :doc:`MoneyType </reference/forms/types/money>`
* :doc:`NumberType </reference/forms/types/number>`
* :doc:`PasswordType </reference/forms/types/password>`
* :doc:`PercentType </reference/forms/types/percent>`
* :doc:`SearchType </reference/forms/types/search>`
* :doc:`UrlType </reference/forms/types/url>`
* :doc:`RangeType </reference/forms/types/range>`
* :doc:`TelType </reference/forms/types/tel>`
* :doc:`ColorType </reference/forms/types/color>`

Choice Fields
~~~~~~~~~~~~~

* :doc:`ChoiceType </reference/forms/types/choice>`
* :doc:`EnumType </reference/forms/types/enum>`
* :doc:`EntityType </reference/forms/types/entity>`
* :doc:`CountryType </reference/forms/types/country>`
* :doc:`LanguageType </reference/forms/types/language>`
* :doc:`LocaleType </reference/forms/types/locale>`
* :doc:`TimezoneType </reference/forms/types/timezone>`
* :doc:`CurrencyType </reference/forms/types/currency>`

Date and Time Fields
~~~~~~~~~~~~~~~~~~~~

* :doc:`DateType </reference/forms/types/date>`
* :doc:`DateIntervalType </reference/forms/types/dateinterval>`
* :doc:`DateTimeType </reference/forms/types/datetime>`
* :doc:`TimeType </reference/forms/types/time>`
* :doc:`BirthdayType </reference/forms/types/birthday>`
* :doc:`WeekType </reference/forms/types/week>`

Other Fields
~~~~~~~~~~~~

* :doc:`CheckboxType </reference/forms/types/checkbox>`
* :doc:`FileType </reference/forms/types/file>`
* :doc:`RadioType </reference/forms/types/radio>`

Symfony UX Fields
~~~~~~~~~~~~~~~~~

These types are part of the `Symfony UX Packages`_

* `CropperType`_ (using Cropper.js)
* `DropzoneType`_

UID Fields
~~~~~~~~~~

* :doc:`UuidType </reference/forms/types/uuid>`
* :doc:`UlidType </reference/forms/types/ulid>`

Field Groups
~~~~~~~~~~~~

* :doc:`CollectionType </reference/forms/types/collection>`
* :doc:`RepeatedType </reference/forms/types/repeated>`

Hidden Fields
~~~~~~~~~~~~~

* :doc:`HiddenType </reference/forms/types/hidden>`

Buttons
~~~~~~~

* :doc:`ButtonType </reference/forms/types/button>`
* :doc:`ResetType </reference/forms/types/reset>`
* :doc:`SubmitType </reference/forms/types/submit>`

Base Fields
~~~~~~~~~~~

* :doc:`FormType </reference/forms/types/form>`

.. _`CropperType`: https://github.com/symfony/ux/tree/2.x/src/Cropperjs#readme
.. _`DropzoneType`: https://github.com/symfony/ux/tree/2.x/src/Dropzone#readme
.. _Symfony UX Packages: https://symfony.com/bundles/StimulusBundle/current/index.html#ux-packages
