* **Templating**:

  * `Twig`_ |
  * :doc:`PHP </guides/templating/PHP>` |
  * :doc:`Recipes </guides/templating/recipes>`

* **Doctrine**:

  * :doc:`DBAL </guides/doctrine/dbal/index>` |
  * :doc:`ORM </guides/doctrine/orm/index>` |
  * :doc:`Migrations </guides/doctrine/migrations/index>` |
  * :doc:`MongoDB </guides/doctrine/mongodb-odm/index>`

* **Testing**:

  * :doc:`Overview </guides/testing/overview>` |
  * :doc:`Configuration </guides/testing/configuration>` |
  * :doc:`Crawler </guides/testing/crawler>` |
  * :doc:`Client </guides/testing/client>` |
  * :doc:`Recipes </guides/testing/recipes>`

* **Validation**:

  * :doc:`Overview </guides/validator/overview>` |
  * :doc:`Validation </guides/validator/validation>` |
  * :doc:`/guides/validator/constraints`

* **Forms**:

  * :doc:`Overview </guides/forms/overview>` |
  * :doc:`Templates </guides/forms/view>` |
  * :doc:`Form Fields </guides/forms/fields>`

* **Security**:

  * :doc:`Overview </guides/security/overview>` |
  * :doc:`/guides/security/users` |
  * :doc:`/guides/security/authentication` |
  * :doc:`/guides/security/authorization` |
  * :doc:`ACLs </guides/security/acl>` |
  * :doc:`Advanced ACLs </guides/security/acl_advanced>` |
  * :doc:`Configuration Reference </guides/security/config_reference>`

* **Cache**:

  * :doc:`/guides/cache/http`

* :doc:`/guides/emails`
* :doc:`/guides/translation`
* **Event Dispatcher**:

  * :doc:`Overview </guides/event/overview>` |
  * :doc:`Recipes </guides/event/recipes>`

* **Tools**:

  * :doc:`/guides/tools/autoloader` |
  * :doc:`Finder </guides/tools/finder>` |
  * :doc:`/guides/tools/YAML`

* **Bundles**:

  * :doc:`Best Practices </guides/bundles/best_practices>` |
  * :doc:`Configuration </guides/bundles/configuration>`

* **Dependency Injection**:

  * :doc:`The Service Container </guides/dependency_injection/overview>` |
  * :doc:`Extensions </guides/dependency_injection/extensions>`

* **Internals**:

  * :doc:`Overview </guides/internals/overview>` |
  * :doc:`Kernel </guides/internals/kernel>` |
  * :doc:`Profiler </guides/internals/profiler>`

* :doc:`Symfony2 for symfony 1 users</guides/symfony1>`
* :doc:`Symfony2 stable API</guides/stable_api>`

.. _Twig: http://www.twig-project.org/documentation
