* :doc:`SensioFrameworkExtraBundle </bundles/SensioFrameworkExtraBundle/index>`
* :doc:`SensioGeneratorBundle </bundles/SensioGeneratorBundle/index>`
* :doc:`JMSSecurityExtraBundle </bundles/JMSSecurityExtraBundle/index>`
* :doc:`DoctrineFixturesBundle </bundles/DoctrineFixturesBundle/index>`
* :doc:`DoctrineMigrationsBundle </bundles/DoctrineMigrationsBundle/index>`
* :doc:`DoctrineMongoDBBundle </bundles/DoctrineMongoDBBundle/index>`
