* :doc:`SensioFrameworkExtraBundle </bundles/SensioFrameworkExtraBundle/index>`
* :doc:`SensioGeneratorBundle </bundles/SensioGeneratorBundle/index>`
* `JMSSecurityExtraBundle`_
* `JMSDiExtraBundle`_
* :doc:`DoctrineFixturesBundle </bundles/DoctrineFixturesBundle/index>`
* :doc:`DoctrineMigrationsBundle </bundles/DoctrineMigrationsBundle/index>`
* :doc:`DoctrineMongoDBBundle </bundles/DoctrineMongoDBBundle/index>`

.. _`JMSSecurityExtraBundle`: http://jmsyst.com/bundles/JMSSecurityExtraBundle/1.2
.. _`JMSDiExtraBundle`: http://jmsyst.com/bundles/JMSDiExtraBundle/1.1
