You can use the following parameters in this message:

===============  ==============================================================
Parameter        Description
===============  ==============================================================
``{{ file }}``   Absolute file path
``{{ name }}``   Base file name
``{{ type }}``   The MIME type of the given file
``{{ types }}``  The list of allowed MIME types
===============  ==============================================================
