Basic Constraints
~~~~~~~~~~~~~~~~~

These are the basic constraints: use them to assert very basic things about
the value of properties or the return value of methods on your object.

* :doc:`NotBlank </reference/constraints/NotBlank>`
* :doc:`Blank </reference/constraints/Blank>`
* :doc:`NotNull </reference/constraints/NotNull>`
* :doc:`Null </reference/constraints/Null>`
* :doc:`True </reference/constraints/True>`
* :doc:`False </reference/constraints/False>`
* :doc:`Type </reference/constraints/Type>`

String Constraints
~~~~~~~~~~~~~~~~~~

* :doc:`Email </reference/constraints/Email>`
* :doc:`MinLength </reference/constraints/MinLength>`
* :doc:`MaxLength </reference/constraints/MaxLength>`
* :doc:`Length </reference/constraints/Length>`
* :doc:`Url </reference/constraints/Url>`
* :doc:`Regex </reference/constraints/Regex>`
* :doc:`Ip </reference/constraints/Ip>`

Number Constraints
~~~~~~~~~~~~~~~~~~

* :doc:`Max </reference/constraints/Max>`
* :doc:`Min </reference/constraints/Min>`
* :doc:`Range </reference/constraints/Range>`

Date Constraints
~~~~~~~~~~~~~~~~

* :doc:`Date </reference/constraints/Date>`
* :doc:`DateTime </reference/constraints/DateTime>`
* :doc:`Time </reference/constraints/Time>`

Collection Constraints
~~~~~~~~~~~~~~~~~~~~~~

* :doc:`Choice </reference/constraints/Choice>`
* :doc:`Collection </reference/constraints/Collection>`
* :doc:`Count </reference/constraints/Count>`
* :doc:`UniqueEntity </reference/constraints/UniqueEntity>`
* :doc:`Language </reference/constraints/Language>`
* :doc:`Locale </reference/constraints/Locale>`
* :doc:`Country </reference/constraints/Country>`

File Constraints
~~~~~~~~~~~~~~~~

* :doc:`File </reference/constraints/File>`
* :doc:`Image </reference/constraints/Image>`

Other Constraints
~~~~~~~~~~~~~~~~~

* :doc:`Callback </reference/constraints/Callback>`
* :doc:`All </reference/constraints/All>`
* :doc:`UserPassword </reference/constraints/UserPassword>`
* :doc:`Valid </reference/constraints/Valid>`
