* :doc:`/cookbook/assetic/index`

  * :doc:`/cookbook/assetic/asset_management`
  * :doc:`/cookbook/assetic/php`
  * :doc:`/cookbook/assetic/uglifyjs`
  * :doc:`/cookbook/assetic/yuicompressor`
  * :doc:`/cookbook/assetic/jpeg_optimize`
  * :doc:`/cookbook/assetic/apply_to_option`

* :doc:`/cookbook/bundles/index`

  * :doc:`/cookbook/bundles/installation`
  * :doc:`/cookbook/bundles/best_practices`
  * :doc:`/cookbook/bundles/inheritance`
  * :doc:`/cookbook/bundles/override`
  * :doc:`/cookbook/bundles/remove`
  * :doc:`/cookbook/bundles/extension`
  * :doc:`/cookbook/bundles/configuration`
  * :doc:`/cookbook/bundles/prepend_extension`

* :doc:`/cookbook/cache/index`

  * :doc:`/cookbook/cache/varnish`
  * :doc:`/cookbook/cache/form_csrf_caching`

* **Composer**

  * :doc:`/cookbook/composer`

* :doc:`/cookbook/configuration/index`

  * :doc:`/cookbook/configuration/environments`
  * :doc:`/cookbook/configuration/micro-kernel-trait`
  * :doc:`/cookbook/configuration/override_dir_structure`
  * :doc:`/cookbook/configuration/using_parameters_in_dic`
  * :doc:`/cookbook/configuration/front_controllers_and_kernel`
  * :doc:`/cookbook/configuration/external_parameters`
  * :doc:`/cookbook/configuration/apache_router`
  * :doc:`/cookbook/configuration/web_server_configuration`
  * :doc:`/cookbook/configuration/configuration_organization`
  * (Doctrine) :doc:`/cookbook/doctrine/pdo_session_storage`
  * (Doctrine) :doc:`/cookbook/doctrine/mongodb_session_storage`

* :doc:`/cookbook/console/index`

  * :doc:`/cookbook/console/console_command`
  * :doc:`/cookbook/console/usage`
  * :doc:`/cookbook/console/style`
  * :doc:`/cookbook/console/command_in_controller`
  * :doc:`/cookbook/console/sending_emails`
  * :doc:`/cookbook/console/logging`
  * :doc:`/cookbook/console/commands_as_services`

* :doc:`/cookbook/controller/index`

  * :doc:`/cookbook/controller/error_pages`
  * :doc:`/cookbook/controller/service`
  * :doc:`/cookbook/controller/upload_file`

* **Debugging**

  * :doc:`/cookbook/debugging`

* :doc:`/cookbook/deployment/index`

  * :doc:`/cookbook/deployment/tools`
  * :doc:`/cookbook/deployment/azure-website`
  * :doc:`/cookbook/deployment/heroku`
  * :doc:`/cookbook/deployment/platformsh`

* :doc:`/cookbook/doctrine/index`

  * :doc:`/cookbook/doctrine/file_uploads`
  * :doc:`/cookbook/doctrine/common_extensions`
  * :doc:`/cookbook/doctrine/event_listeners_subscribers`
  * :doc:`/cookbook/doctrine/dbal`
  * :doc:`/cookbook/doctrine/reverse_engineering`
  * :doc:`/cookbook/doctrine/multiple_entity_managers`
  * :doc:`/cookbook/doctrine/custom_dql_functions`
  * :doc:`/cookbook/doctrine/resolve_target_entity`
  * :doc:`/cookbook/doctrine/mapping_model_classes`
  * :doc:`/cookbook/doctrine/registration_form`
  * :doc:`/cookbook/doctrine/pdo_session_storage`
  * :doc:`/cookbook/doctrine/mongodb_session_storage`
  * :doc:`/cookbook/doctrine/console`

* :doc:`/cookbook/email/index`

  * :doc:`/cookbook/email/email`
  * :doc:`/cookbook/email/gmail`
  * :doc:`/cookbook/email/cloud`
  * :doc:`/cookbook/email/dev_environment`
  * :doc:`/cookbook/email/spool`
  * :doc:`/cookbook/email/testing`

* :doc:`/cookbook/event_dispatcher/index`

  * :doc:`/cookbook/event_dispatcher/before_after_filters`
  * :doc:`/cookbook/event_dispatcher/class_extension`
  * :doc:`/cookbook/event_dispatcher/method_behavior`
  * :doc:`/cookbook/event_dispatcher/event_listener`

* :doc:`/cookbook/expression/index`

  * :doc:`/cookbook/expression/expressions`

* :doc:`/cookbook/form/index`

  * :doc:`/cookbook/form/form_customization`
  * :doc:`/cookbook/form/data_transformers`
  * :doc:`/cookbook/form/dynamic_form_modification`
  * :doc:`/cookbook/form/form_collections`
  * :doc:`/cookbook/form/create_custom_field_type`
  * :doc:`/cookbook/form/create_form_type_extension`
  * :doc:`/cookbook/form/inherit_data_option`
  * :doc:`/cookbook/form/unit_testing`
  * :doc:`/cookbook/form/use_empty_data`
  * :doc:`/cookbook/form/direct_submit`
  * (Validation) :doc:`/cookbook/validation/custom_constraint`
  * (Doctrine) :doc:`/cookbook/doctrine/file_uploads`

* :doc:`/cookbook/frontend/index`

  * :doc:`/cookbook/frontend/bower`

* :doc:`/cookbook/install/index`

  * :doc:`/cookbook/install/unstable_versions`

* :doc:`/cookbook/logging/index`

  * :doc:`/cookbook/logging/monolog`
  * :doc:`/cookbook/logging/monolog_email`
  * :doc:`/cookbook/logging/monolog_console`
  * :doc:`/cookbook/logging/monolog_regex_based_excludes`
  * :doc:`/cookbook/logging/channels_handlers`

* :doc:`/cookbook/profiler/index`

  * :doc:`/cookbook/profiler/data_collector`
  * :doc:`/cookbook/profiler/matchers`
  * :doc:`/cookbook/profiler/storage`
  * :doc:`/cookbook/profiler/profiling_data`

* :doc:`/cookbook/request/index`

  * :doc:`/cookbook/request/load_balancer_reverse_proxy`
  * :doc:`/cookbook/request/mime_type`
  * (session) :doc:`/cookbook/session/locale_sticky_session`

* :doc:`/cookbook/routing/index`

  * :doc:`/cookbook/routing/scheme`
  * :doc:`/cookbook/routing/slash_in_parameter`
  * :doc:`/cookbook/routing/redirect_in_config`
  * :doc:`/cookbook/routing/method_parameters`
  * :doc:`/cookbook/routing/service_container_parameters`
  * :doc:`/cookbook/routing/custom_route_loader`
  * :doc:`/cookbook/routing/redirect_trailing_slash`
  * :doc:`/cookbook/routing/extra_information`

* :doc:`Security Authentication (Identifying/Logging in the User) </cookbook/security/index>`

  * :doc:`/cookbook/security/form_login_setup`
  * :doc:`/cookbook/security/entity_provider`
  * :doc:`/cookbook/security/guard-authentication`
  * :doc:`/cookbook/security/remember_me`
  * :doc:`/cookbook/security/impersonating_user`
  * :doc:`/cookbook/security/form_login`
  * :doc:`/cookbook/security/custom_provider`
  * :doc:`/cookbook/security/custom_password_authenticator`
  * :doc:`/cookbook/security/api_key_authentication`
  * :doc:`/cookbook/security/custom_authentication_provider`
  * :doc:`/cookbook/security/pre_authenticated`
  * :doc:`/cookbook/security/target_path`
  * :doc:`/cookbook/security/csrf_in_login_form`
  * :doc:`/cookbook/security/named_encoders`
  * :doc:`/cookbook/security/multiple_user_providers`
  * :doc:`/cookbook/security/firewall_restriction`
  * :doc:`/cookbook/security/host_restriction`

* :doc:`Security Authorization (Denying Access) </cookbook/security/index>`

  * :doc:`/cookbook/security/voters`
  * :doc:`/cookbook/security/acl`
  * :doc:`/cookbook/security/acl_advanced`
  * :doc:`/cookbook/security/force_https`
  * :doc:`/cookbook/security/securing_services`
  * :doc:`/cookbook/security/access_control`

* **Serializer**

  * :doc:`/cookbook/serializer`

* :doc:`/cookbook/service_container/index`

  * :doc:`/cookbook/service_container/shared`
  * :doc:`/cookbook/service_container/compiler_passes`
  * (Event Dispatcher) :doc:`/cookbook/event_dispatcher/event_listener`

* :doc:`/cookbook/session/index`

  * :doc:`/cookbook/session/proxy_examples`
  * :doc:`/cookbook/session/locale_sticky_session`
  * :doc:`/cookbook/session/sessions_directory`
  * :doc:`/cookbook/session/php_bridge`
  * :doc:`/cookbook/session/limit_metadata_writes`
  * (Doctrine) :doc:`/cookbook/doctrine/pdo_session_storage`
  * (Doctrine) :doc:`/cookbook/doctrine/mongodb_session_storage`
  * :doc:`/cookbook/session/avoid_session_start`


* **PSR-7**

  * :doc:`/cookbook/psr7`

* :doc:`/cookbook/templating/index`

  * :doc:`/cookbook/templating/global_variables`
  * :doc:`/cookbook/templating/namespaced_paths`
  * :doc:`/cookbook/templating/PHP`
  * :doc:`/cookbook/templating/twig_extension`
  * :doc:`/cookbook/templating/render_without_controller`

* :doc:`/cookbook/testing/index`

  * :doc:`/cookbook/testing/http_authentication`
  * :doc:`/cookbook/testing/simulating_authentication`
  * :doc:`/cookbook/testing/insulating_clients`
  * :doc:`/cookbook/testing/profiling`
  * :doc:`/cookbook/testing/database`
  * :doc:`/cookbook/testing/doctrine`
  * :doc:`/cookbook/testing/bootstrap`
  * (email) :doc:`/cookbook/email/testing`
  * (form) :doc:`/cookbook/form/unit_testing`

* :doc:`/cookbook/upgrade/index`

  * :doc:`/cookbook/upgrade/patch_version`
  * :doc:`/cookbook/upgrade/minor_version`
  * :doc:`/cookbook/upgrade/major_version`

* :doc:`/cookbook/validation/index`

  * :doc:`/cookbook/validation/custom_constraint`
  * :doc:`/cookbook/validation/severity`

* :doc:`/cookbook/web_server/index`

  * :doc:`/cookbook/web_server/built_in`
  * (configuration) :doc:`/cookbook/configuration/web_server_configuration`

* :doc:`/cookbook/web_services/index`

  * :doc:`/cookbook/web_services/php_soap_extension`

* :doc:`/cookbook/workflow/index`

  * :doc:`/cookbook/workflow/new_project_git`
  * :doc:`/cookbook/workflow/new_project_svn`
