* **Code of Conduct**

  * :doc:`/code_of_conduct/conde_of_conduct`
  * :doc:`/code_of_conduct/reporting_guidelines`
  * :doc:`/code_of_conduct/enforcement_team`
  * :doc:`/code_of_conduct/concrete_example_document`

* **Code**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Reviewing Issues and Patches </contributing/community/reviews>`
  * :doc:`Maintenance </contributing/code/maintenance>`
  * :doc:`The Core Team </contributing/code/core_team>`
  * :doc:`Security </contributing/code/security>`
  * :doc:`Tests </contributing/code/tests>`
  * :doc:`Backward Compatibility </contributing/code/bc>`
  * :doc:`Coding Standards</contributing/code/standards>`
  * :doc:`Code Conventions</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`License </contributing/code/license>`

* **Documentation**

  * :doc:`Overview </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Documentation Standards </contributing/documentation/standards>`
  * :doc:`License </contributing/documentation/license>`

* **Community**

  * :doc:`Release Process </contributing/community/releases>`
  * :doc:`Respectful Review comments </contributing/community/review-comments>`
  * :doc:`Community Reviews </contributing/community/reviews>`
  * :doc:`Other Resources </contributing/community/other>`
