* **Code**:

  * :doc:`Bugs </contributing/code/bugs>` | 
  * :doc:`Patches </contributing/code/patches>` | 
  * :doc:`Security </contributing/code/security>` | 
  * :doc:`Tests </contributing/code/tests>` | 
  * :doc:`Coding Standards</contributing/code/standards>` | 
  * :doc:`Code Conventions</contributing/code/conventions>` | 
  * :doc:`License </contributing/code/license>`

* **Documentation**:

  * :doc:`Overview </contributing/documentation/overview>` | 
  * :doc:`Format </contributing/documentation/format>` | 
  * :doc:`Translations </contributing/documentation/translations>` | 
  * :doc:`License </contributing/documentation/license>`

* **Community**:

  * :doc:`IRC Meetings </contributing/community/irc>` |
  * :doc:`Other Resources </contributing/community/other>`
