* :doc:`Symfony2 Fundamentals </book/http_fundamentals>`
* :doc:`When flat PHP meets Symfony </book/from_flat_php_to_symfony2>`

* :doc:`Installing and Configuring Symfony </book/installation>`
* :doc:`The Basics of Page Creation </book/page_creation>`

* :doc:`Controllers </book/controller>`
* :doc:`Routing </book/routing>`
* :doc:`Templating </book/templating>`
* :doc:`Testing </book/testing>`

* **Doctrine**:

  * :doc:`Introduction to the Model </book/doctrine/model>` |
  * :doc:`DBAL </book/doctrine/dbal>` |
  * :doc:`ORM </book/doctrine/orm>`

* :doc:`Validation </book/validation>`
* :doc:`Forms </book/forms>`
* :doc:`Security </book/security>`

* :doc:`/book/http_cache`
* :doc:`/book/translation`
* :doc:`Bundles </book/bundles>`
* :doc:`The Service Container </book/service_container>`

* **Internals**:

  * :doc:`Overview </book/internals/overview>` |
  * :doc:`Kernel </book/internals/kernel>` |
  * :doc:`Event Dispatcher </book/internals/event_dispatcher>` |
  * :doc:`Profiler </book/internals/profiler>`

* :doc:`Symfony2 stable API</book/stable_api>`

.. _Twig Templating: http://www.twig-project.org/documentation
